GET https://phonebook-bob.herokuapp.com/api/persons/

###
POST https://phonebook-bob.herokuapp.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number":"867 5309"
}

###
DELETE https://phonebook-bob.herokuapp.com/api/persons/5 HTTP/1.1
content-type: application/json